sf_ai_integration_tests:
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'test_account') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'test_user') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'test_password') }}"
      authenticator: snowflake
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'test_database') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'test_warehouse') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'SF_AI_INTEGRATION_TESTS') }}"
      threads: 4
      client_session_keep_alive: false
